name: build-32-bit
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x]
    name: Build with Go ${{ matrix.go-version }} 32-bit
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          stable: false
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: GOARCH=386 go test -v ./...
