name: build
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x, 1.22.x]
    name: Build with Go ${{ matrix.go-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2023.1.7"
          install-go: false
          cache-key: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v ./...

      - name: Run tests with race detector
        run: go test -timeout 10m -race -v ./...
